### ISSUE TITLE
New extension: <Speed Tracker>

### ISSUE THREAD

**Issue by UnknownUney** [GDevelopApp/GDevelop-extensions#1319]
### Description

This extension tracks the speed of the assigned about in pixels. This uses the FPS extension to make it work

### How to use the extension

If you put the behavior on a sprite, you are able to track and detect the current X and Y speed of said sprite.

### Checklist

- [X] I've followed all of [the best practices](http://wiki.compilgames.net/doku.php/gdevelop5/extensions/best-practices).
- [X] I confirm that this extension can be integrated to this GitHub repository, distributed and MIT licensed.
- [X] I am aware that the extension may be updated by anyone, and do not need my explicit consent to do so.

### What tier of review do you aim for your extension?

Reviewed

### Example file

[STT.zip](https://github.com/user-attachments/files/15862282/STT.zip)

### Extension file

[SpeedTracker v1.0.0.zip](https://github.com/user-attachments/files/15862284/SpeedTracker.v1.0.0.zip)
